from jinja2 import Environment, FileSystemLoader
import os
from datetime import datetime
import pdfkit

def generate_report(validation, anomalies, figures, summary, insights=None, output_path="outputs/report.html"):
    print("📝 Generating styled HTML + PDF report with Jinja2...")

    # Load template
    env = Environment(loader=FileSystemLoader("templates"))
    template = env.get_template("report_template.html")

    # Add metadata (timestamp + branding footer)
    footer = {
        "generated_on": datetime.now().strftime("%d %B %Y, %I:%M %p"),
        "branding": "Generated by Excel Data Cleaner Bot – Summer Internship Project, 2025"
    }

    # Render HTML
    html_content = template.render(
        validation=validation,
        anomalies=anomalies,
        figures=figures,
        summary=summary,
        insights=insights or {},   # ✅ predictive insights
        footer=footer
    )

    # Ensure output folder exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Save HTML
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"✅ HTML Report saved to {output_path}")

    # Save PDF version
    pdf_path = output_path.replace(".html", ".pdf")
    pdfkit.from_string(html_content, pdf_path)
    print(f"✅ PDF Report saved to {pdf_path}")